### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by yihui-he** [ab8266339/Javatest#3]
netbeans 好像可以import的，不过我把netbeans删了，现在用intellij :)

**Comment by ab8266339** [comment]
Netbeans is fine, I was just too dummy to find that actually it imports project directly.

**Comment by ab8266339** [comment]
学校电脑不便打中文。怎么样把eclipse 导进netbeans ？

**Comment by yihui-he** [comment]
File > Import Project > Eclipse Project.
